[project]
name = "fdtd"
version = "0.1.0"
description = "A python project for Electromagnetic Simulation using FDTD"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pyqt6>=6.9.1",
]
